name: "Release to prod"
description: "Pretend this released to production"

runs:
  using: "composite"
  steps:
    - name: print out stuff
      run: |
        echo "${{github.ref}}"
        echo "${{github.head_ref}}"
        echo "${{github.ref_name}}"
        git rev-parse --abbrev-ref HEAD
      shell: bash

    - name: Do some release stuff for main
      if: github.ref == 'refs/heads/main'
      run: |
        echo "this is the release script for main"
      shell: bash


    - name: Do some release stuff for a hotfix
      if: contains(github.ref, 'hotfix') == true
      run: |
        echo "this is the release script for a HOTFIX"
      shell: bash

    - name: Warn about other branches
      if: contains(github.ref, 'hotfix') == false && github.ref != 'refs/head/main'
      run: |
        echo "Can only release main or hotfix"
      shell: bash
