name: "Release to prod"
description: "Pretend this released to production"

runs:
  using: "composite"
  steps:
    - name: print out stuff
      run: |
        echo "${{github.event.release.target_commitish}}"
      shell: bash

    - name: Do some release stuff for main
      if: github.event.release.target_commitish == 'main'
      run: |
        echo "this is the release script for main"
      shell: bash
