name: "Release to prod"
description: "Pretend this released to production"

runs:
  using: "composite"
  steps:
    - name: print out stuff
      # on pr
      # echo "${{github.ref}}" -> refs/pull/7/merge
      # echo "${{github.head_ref}}" -> jblock/gh-debug-1  # but this is only available on `pull_request`, not release
      # echo "${{github.ref_name}}" -> 7/merge
      # git rev-parse --abbrev-ref HEAD -> HEAD
      run: |
        echo "${{github.event.release.target_commitish}}"
        echo "${{ toJson(github) }}"
      shell: bash

    - name: Do some release stuff for main
      if: github.event.target_commitish == 'main'
      run: |
        echo "this is the release script for main"
      shell: bash


    - name: Do some release stuff for a hotfix
      if: contains(github.event.release.target_commitish, 'hotfix') == true
      run: |
        echo "this is the release script for a HOTFIX"
      shell: bash

    - name: Warn about other branches
      if: github.event.release.target_commitish != 'main'
      run: |
        echo "Can only release main or hotfix"
      shell: bash
