name: Release

on:
  release:
    types: [published]
    paths-ignore:
      - '**.md'

jobs:
  release:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Release magic"
        uses: ./.github/actions/release_to_prod