name: Release

on:
#  pull_request:
#    branches:
#      - '*'

  release:
    types: [published]
    paths-ignore:
      - '**.md'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Release magic"
        uses: ./.github/actions/release_to_prod